In [72]:
import numpy as np

### Creating integers from 30 to 70 in an array

In [73]:
arr = np.arange(30,71)

In [74]:
print("Array of integers from 30 to 70 is : ", arr)

Array of integers from 30 to 70 is :  [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### Generating 15 random numbers from standard distribution

In [75]:
random = np.random.randn(15)

In [76]:
print("15 random numbers are : ",random)

15 random numbers are :  [-0.37388619  0.58451893 -1.77892756 -0.73922433 -0.25364959  1.2338866
  0.97914393 -0.14157395 -0.0122446   0.4703333  -0.76605633  0.23085611
 -0.10720805  0.5238696   0.60368951]


### Taking cross product of two matrices

In [77]:
matrix1 = np.array([[1,2,3],[3,2,1],[2,3,1]])
matrix2 = np.array([[4,5,6],[6,5,4],[5,6,4]])
cross_product = np.cross(matrix1, matrix2)

In [78]:
print("Matrix 1 is : \n", matrix1)
print("Matrix 2 is : \n", matrix2)
print("Cross product of matrix 1 and matrix 2 is : \n",cross_product)

Matrix 1 is : 
 [[1 2 3]
 [3 2 1]
 [2 3 1]]
Matrix 2 is : 
 [[4 5 6]
 [6 5 4]
 [5 6 4]]
Cross product of matrix 1 and matrix 2 is : 
 [[-3  6 -3]
 [ 3 -6  3]
 [ 6 -3 -3]]


### Taking determinant of matrix

In [79]:
matrix = np.array([[3,4],[1,2]])

In [80]:
det = np.linalg.det(matrix)

In [81]:
print("Determinant of matrix \n", matrix, "is ", det)

Determinant of matrix 
 [[3 4]
 [1 2]] is  2.0000000000000004


### Creating a 3x3x3 array of random numbers

In [82]:
arr = np.random.rand(3,3,3)

In [83]:
print("3x3x3 array of random numbers is : \n", arr)

3x3x3 array of random numbers is : 
 [[[0.67319184 0.73854765 0.83943109]
  [0.61881768 0.60316329 0.62322714]
  [0.49063019 0.51886723 0.68786995]]

 [[0.63719503 0.35060488 0.92441694]
  [0.62595653 0.98731709 0.30883835]
  [0.52683577 0.16035018 0.80589768]]

 [[0.30892706 0.06353617 0.65450822]
  [0.53965246 0.28991471 0.74393246]
  [0.38162673 0.6110889  0.88885434]]]


### Generating a random 5x5 array and finding minimum and maximum values

In [84]:
arr = np.random.rand(5,5)

In [85]:
print("5x5 array of random numbers is : \n", arr)

5x5 array of random numbers is : 
 [[0.7090906  0.61759805 0.19496446 0.2740927  0.11191494]
 [0.11210764 0.31434713 0.61498296 0.56621727 0.82662493]
 [0.20084286 0.11201142 0.97261512 0.88125701 0.33438606]
 [0.41141844 0.1227937  0.32209418 0.87615261 0.15929265]
 [0.75928061 0.97906143 0.23981166 0.64147442 0.46477438]]


In [86]:
print("Maximum element inside array is : ", np.amax(arr))

Maximum element inside array is :  0.9790614260732774


In [87]:
print("Minumum element inside array is : ", np.amin(arr))

Minumum element inside array is :  0.11191493507517947


### Computing mean, variance and standard deviation of second axis

In [88]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
mean = np.mean(arr, axis = 1)
variance = np.var(arr, axis = 1)
std = np.std(arr, axis = 1)

In [90]:
print("Mean of second axis array is : " + str(mean))
print("Variance of second axis array is : " + str(variance))
print("Standard deviation of second axis array is : " + str(std))

Mean of second axis array is : [2. 5. 8.]
Variance of second axis array is : [0.66666667 0.66666667 0.66666667]
Standard deviation of second axis array is : [0.81649658 0.81649658 0.81649658]
